[tool.poetry]
name = "media-parser"
version = "0.1.3"
description = "Simple Telegraph media parser"
authors = ["FruitApple"]

[tool.poetry.dependencies]
python = "^3.12"
tuparser = "^0.1.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
